import type { FastifyPluginAsync } from "fastify";
import { adminRoutes } from "./admin.js";
import { battleRoutes } from "./battles.js";
import { cameraRoutes } from "./camera.js";
import { gameRoutes } from "./games.js";
import { dashboardRoutes } from "./dashboard.js";
import { discoveryRoutes } from "./discovery.js";
import { giftRoutes } from "./gifts.js";
import { goalRoutes } from "./goals.js";
import { healthRoutes } from "./health.js";
import { coLiveRoutes } from "./colive.js";
import { consoleRoutes } from "./console.js";
import { ruleRoutes } from "./rules.js";
import { analyticsRoutes } from "./analytics.js";
import { controlRoutes } from "./control.js";
import { appealRoutes } from "./appeals.js";
import { guestRoutes } from "./guests.js";
import { marketDirectorRoutes } from "./market-director.js";
import { marketRoutes } from "./market.js";
import { moderationRoutes } from "./moderation.js";
import { notificationRoutes } from "./notifications.js";
import { requestRoutes } from "./requests.js";
import { rundownRoutes } from "./rundown.js";
import { rewardRoutes } from "./rewards.js";
import { safetyRoutes } from "./safety.js";
import { sponsorRoutes } from "./sponsors.js";
import { streamActionRoutes } from "./stream-actions.js";
import { streamRoutes } from "./streams.js";
import { userRoutes } from "./users.js";
import { webhookRoutes } from "./webhooks.js";

export const apiRoutes: FastifyPluginAsync = async (fastify) => {
  await fastify.register(userRoutes);
  await fastify.register(streamRoutes);
  await fastify.register(streamActionRoutes);
  await fastify.register(discoveryRoutes);
  await fastify.register(dashboardRoutes);
  await fastify.register(giftRoutes);
  await fastify.register(goalRoutes);
  await fastify.register(requestRoutes);
  await fastify.register(sponsorRoutes);
  await fastify.register(rundownRoutes);
  await fastify.register(consoleRoutes);
  await fastify.register(cameraRoutes);
  await fastify.register(ruleRoutes);
  await fastify.register(analyticsRoutes);
  await fastify.register(controlRoutes);
  await fastify.register(appealRoutes);
  await fastify.register(healthRoutes);
  await fastify.register(battleRoutes);
  await fastify.register(gameRoutes);
  await fastify.register(rewardRoutes);
  await fastify.register(guestRoutes);
  await fastify.register(coLiveRoutes);
  await fastify.register(moderationRoutes);
  await fastify.register(safetyRoutes);
  await fastify.register(adminRoutes);
  await fastify.register(marketRoutes);
  await fastify.register(marketDirectorRoutes);
  await fastify.register(notificationRoutes);
  await fastify.register(webhookRoutes);
};
