/**
 * Xtream's icon set: Solar (480 Design, CC BY 4.0) via Iconify data, drawn
 * inline. One component per name the app already used with Phosphor, so
 * the swap (owner, 2026-09-24: "a fancier, more beautiful library") cost
 * no call-site changes. Phosphor's `weight` maps onto Solar's styles:
 * regular → Linear, bold → Outline, fill → Bold, duotone → Bold Duotone.
 * The bare X isn't in Solar, so it's drawn here.
 */
import type { CSSProperties, SVGProps } from "react";

import i_add_linear from "@iconify-icons/solar/add-linear";
import i_add_outline from "@iconify-icons/solar/add-outline";
import i_add_bold from "@iconify-icons/solar/add-bold";
import i_add_bold_duotone from "@iconify-icons/solar/add-bold-duotone";
import i_alt_arrow_down_linear from "@iconify-icons/solar/alt-arrow-down-linear";
import i_alt_arrow_down_outline from "@iconify-icons/solar/alt-arrow-down-outline";
import i_alt_arrow_down_bold from "@iconify-icons/solar/alt-arrow-down-bold";
import i_alt_arrow_down_bold_duotone from "@iconify-icons/solar/alt-arrow-down-bold-duotone";
import i_alt_arrow_left_linear from "@iconify-icons/solar/alt-arrow-left-linear";
import i_alt_arrow_left_outline from "@iconify-icons/solar/alt-arrow-left-outline";
import i_alt_arrow_left_bold from "@iconify-icons/solar/alt-arrow-left-bold";
import i_alt_arrow_left_bold_duotone from "@iconify-icons/solar/alt-arrow-left-bold-duotone";
import i_alt_arrow_right_linear from "@iconify-icons/solar/alt-arrow-right-linear";
import i_alt_arrow_right_outline from "@iconify-icons/solar/alt-arrow-right-outline";
import i_alt_arrow_right_bold from "@iconify-icons/solar/alt-arrow-right-bold";
import i_alt_arrow_right_bold_duotone from "@iconify-icons/solar/alt-arrow-right-bold-duotone";
import i_alt_arrow_up_linear from "@iconify-icons/solar/alt-arrow-up-linear";
import i_alt_arrow_up_outline from "@iconify-icons/solar/alt-arrow-up-outline";
import i_alt_arrow_up_bold from "@iconify-icons/solar/alt-arrow-up-bold";
import i_alt_arrow_up_bold_duotone from "@iconify-icons/solar/alt-arrow-up-bold-duotone";
import i_arrow_down_linear from "@iconify-icons/solar/arrow-down-linear";
import i_arrow_down_outline from "@iconify-icons/solar/arrow-down-outline";
import i_arrow_down_bold from "@iconify-icons/solar/arrow-down-bold";
import i_arrow_down_bold_duotone from "@iconify-icons/solar/arrow-down-bold-duotone";
import i_arrow_left_linear from "@iconify-icons/solar/arrow-left-linear";
import i_arrow_left_outline from "@iconify-icons/solar/arrow-left-outline";
import i_arrow_left_bold from "@iconify-icons/solar/arrow-left-bold";
import i_arrow_left_bold_duotone from "@iconify-icons/solar/arrow-left-bold-duotone";
import i_arrow_right_linear from "@iconify-icons/solar/arrow-right-linear";
import i_arrow_right_outline from "@iconify-icons/solar/arrow-right-outline";
import i_arrow_right_bold from "@iconify-icons/solar/arrow-right-bold";
import i_arrow_right_bold_duotone from "@iconify-icons/solar/arrow-right-bold-duotone";
import i_arrow_right_up_linear from "@iconify-icons/solar/arrow-right-up-linear";
import i_arrow_right_up_outline from "@iconify-icons/solar/arrow-right-up-outline";
import i_arrow_right_up_bold from "@iconify-icons/solar/arrow-right-up-bold";
import i_arrow_right_up_bold_duotone from "@iconify-icons/solar/arrow-right-up-bold-duotone";
import i_arrow_up_linear from "@iconify-icons/solar/arrow-up-linear";
import i_arrow_up_outline from "@iconify-icons/solar/arrow-up-outline";
import i_arrow_up_bold from "@iconify-icons/solar/arrow-up-bold";
import i_arrow_up_bold_duotone from "@iconify-icons/solar/arrow-up-bold-duotone";
import i_bell_linear from "@iconify-icons/solar/bell-linear";
import i_bell_outline from "@iconify-icons/solar/bell-outline";
import i_bell_bold from "@iconify-icons/solar/bell-bold";
import i_bell_bold_duotone from "@iconify-icons/solar/bell-bold-duotone";
import i_bell_bing_linear from "@iconify-icons/solar/bell-bing-linear";
import i_bell_bing_outline from "@iconify-icons/solar/bell-bing-outline";
import i_bell_bing_bold from "@iconify-icons/solar/bell-bing-bold";
import i_bell_bing_bold_duotone from "@iconify-icons/solar/bell-bing-bold-duotone";
import i_bill_list_linear from "@iconify-icons/solar/bill-list-linear";
import i_bill_list_outline from "@iconify-icons/solar/bill-list-outline";
import i_bill_list_bold from "@iconify-icons/solar/bill-list-bold";
import i_bill_list_bold_duotone from "@iconify-icons/solar/bill-list-bold-duotone";
import i_bluetooth_linear from "@iconify-icons/solar/bluetooth-linear";
import i_bluetooth_outline from "@iconify-icons/solar/bluetooth-outline";
import i_bluetooth_bold from "@iconify-icons/solar/bluetooth-bold";
import i_bluetooth_bold_duotone from "@iconify-icons/solar/bluetooth-bold-duotone";
import i_bolt_linear from "@iconify-icons/solar/bolt-linear";
import i_bolt_outline from "@iconify-icons/solar/bolt-outline";
import i_bolt_bold from "@iconify-icons/solar/bolt-bold";
import i_bolt_bold_duotone from "@iconify-icons/solar/bolt-bold-duotone";
import i_bolt_circle_linear from "@iconify-icons/solar/bolt-circle-linear";
import i_bolt_circle_outline from "@iconify-icons/solar/bolt-circle-outline";
import i_bolt_circle_bold from "@iconify-icons/solar/bolt-circle-bold";
import i_bolt_circle_bold_duotone from "@iconify-icons/solar/bolt-circle-bold-duotone";
import i_calendar_add_linear from "@iconify-icons/solar/calendar-add-linear";
import i_calendar_add_outline from "@iconify-icons/solar/calendar-add-outline";
import i_calendar_add_bold from "@iconify-icons/solar/calendar-add-bold";
import i_calendar_add_bold_duotone from "@iconify-icons/solar/calendar-add-bold-duotone";
import i_calendar_minimalistic_linear from "@iconify-icons/solar/calendar-minimalistic-linear";
import i_calendar_minimalistic_outline from "@iconify-icons/solar/calendar-minimalistic-outline";
import i_calendar_minimalistic_bold from "@iconify-icons/solar/calendar-minimalistic-bold";
import i_calendar_minimalistic_bold_duotone from "@iconify-icons/solar/calendar-minimalistic-bold-duotone";
import i_camera_linear from "@iconify-icons/solar/camera-linear";
import i_camera_outline from "@iconify-icons/solar/camera-outline";
import i_camera_bold from "@iconify-icons/solar/camera-bold";
import i_camera_bold_duotone from "@iconify-icons/solar/camera-bold-duotone";
import i_camera_rotate_linear from "@iconify-icons/solar/camera-rotate-linear";
import i_camera_rotate_outline from "@iconify-icons/solar/camera-rotate-outline";
import i_camera_rotate_bold from "@iconify-icons/solar/camera-rotate-bold";
import i_camera_rotate_bold_duotone from "@iconify-icons/solar/camera-rotate-bold-duotone";
import i_card_linear from "@iconify-icons/solar/card-linear";
import i_card_outline from "@iconify-icons/solar/card-outline";
import i_card_bold from "@iconify-icons/solar/card-bold";
import i_card_bold_duotone from "@iconify-icons/solar/card-bold-duotone";
import i_chart_2_linear from "@iconify-icons/solar/chart-2-linear";
import i_chart_2_outline from "@iconify-icons/solar/chart-2-outline";
import i_chart_2_bold from "@iconify-icons/solar/chart-2-bold";
import i_chart_2_bold_duotone from "@iconify-icons/solar/chart-2-bold-duotone";
import i_chat_line_linear from "@iconify-icons/solar/chat-line-linear";
import i_chat_line_outline from "@iconify-icons/solar/chat-line-outline";
import i_chat_line_bold from "@iconify-icons/solar/chat-line-bold";
import i_chat_line_bold_duotone from "@iconify-icons/solar/chat-line-bold-duotone";
import i_chat_round_linear from "@iconify-icons/solar/chat-round-linear";
import i_chat_round_outline from "@iconify-icons/solar/chat-round-outline";
import i_chat_round_bold from "@iconify-icons/solar/chat-round-bold";
import i_chat_round_bold_duotone from "@iconify-icons/solar/chat-round-bold-duotone";
import i_chat_round_dots_linear from "@iconify-icons/solar/chat-round-dots-linear";
import i_chat_round_dots_outline from "@iconify-icons/solar/chat-round-dots-outline";
import i_chat_round_dots_bold from "@iconify-icons/solar/chat-round-dots-bold";
import i_chat_round_dots_bold_duotone from "@iconify-icons/solar/chat-round-dots-bold-duotone";
import i_check_circle_linear from "@iconify-icons/solar/check-circle-linear";
import i_check_circle_outline from "@iconify-icons/solar/check-circle-outline";
import i_check_circle_bold from "@iconify-icons/solar/check-circle-bold";
import i_check_circle_bold_duotone from "@iconify-icons/solar/check-circle-bold-duotone";
import i_check_read_linear from "@iconify-icons/solar/check-read-linear";
import i_check_read_outline from "@iconify-icons/solar/check-read-outline";
import i_check_read_bold from "@iconify-icons/solar/check-read-bold";
import i_check_read_bold_duotone from "@iconify-icons/solar/check-read-bold-duotone";
import i_clock_circle_linear from "@iconify-icons/solar/clock-circle-linear";
import i_clock_circle_outline from "@iconify-icons/solar/clock-circle-outline";
import i_clock_circle_bold from "@iconify-icons/solar/clock-circle-bold";
import i_clock_circle_bold_duotone from "@iconify-icons/solar/clock-circle-bold-duotone";
import i_code_2_linear from "@iconify-icons/solar/code-2-linear";
import i_code_2_outline from "@iconify-icons/solar/code-2-outline";
import i_code_2_bold from "@iconify-icons/solar/code-2-bold";
import i_code_2_bold_duotone from "@iconify-icons/solar/code-2-bold-duotone";
import i_compass_linear from "@iconify-icons/solar/compass-linear";
import i_compass_outline from "@iconify-icons/solar/compass-outline";
import i_compass_bold from "@iconify-icons/solar/compass-bold";
import i_compass_bold_duotone from "@iconify-icons/solar/compass-bold-duotone";
import i_copy_linear from "@iconify-icons/solar/copy-linear";
import i_copy_outline from "@iconify-icons/solar/copy-outline";
import i_copy_bold from "@iconify-icons/solar/copy-bold";
import i_copy_bold_duotone from "@iconify-icons/solar/copy-bold-duotone";
import i_crown_linear from "@iconify-icons/solar/crown-linear";
import i_crown_outline from "@iconify-icons/solar/crown-outline";
import i_crown_bold from "@iconify-icons/solar/crown-bold";
import i_crown_bold_duotone from "@iconify-icons/solar/crown-bold-duotone";
import i_cup_star_linear from "@iconify-icons/solar/cup-star-linear";
import i_cup_star_outline from "@iconify-icons/solar/cup-star-outline";
import i_cup_star_bold from "@iconify-icons/solar/cup-star-bold";
import i_cup_star_bold_duotone from "@iconify-icons/solar/cup-star-bold-duotone";
import i_danger_circle_linear from "@iconify-icons/solar/danger-circle-linear";
import i_danger_circle_outline from "@iconify-icons/solar/danger-circle-outline";
import i_danger_circle_bold from "@iconify-icons/solar/danger-circle-bold";
import i_danger_circle_bold_duotone from "@iconify-icons/solar/danger-circle-bold-duotone";
import i_danger_triangle_linear from "@iconify-icons/solar/danger-triangle-linear";
import i_danger_triangle_outline from "@iconify-icons/solar/danger-triangle-outline";
import i_danger_triangle_bold from "@iconify-icons/solar/danger-triangle-bold";
import i_danger_triangle_bold_duotone from "@iconify-icons/solar/danger-triangle-bold-duotone";
import i_diskette_linear from "@iconify-icons/solar/diskette-linear";
import i_diskette_outline from "@iconify-icons/solar/diskette-outline";
import i_diskette_bold from "@iconify-icons/solar/diskette-bold";
import i_diskette_bold_duotone from "@iconify-icons/solar/diskette-bold-duotone";
import i_document_linear from "@iconify-icons/solar/document-linear";
import i_document_outline from "@iconify-icons/solar/document-outline";
import i_document_bold from "@iconify-icons/solar/document-bold";
import i_document_bold_duotone from "@iconify-icons/solar/document-bold-duotone";
import i_document_text_linear from "@iconify-icons/solar/document-text-linear";
import i_document_text_outline from "@iconify-icons/solar/document-text-outline";
import i_document_text_bold from "@iconify-icons/solar/document-text-bold";
import i_document_text_bold_duotone from "@iconify-icons/solar/document-text-bold-duotone";
import i_dollar_linear from "@iconify-icons/solar/dollar-linear";
import i_dollar_outline from "@iconify-icons/solar/dollar-outline";
import i_dollar_bold from "@iconify-icons/solar/dollar-bold";
import i_dollar_bold_duotone from "@iconify-icons/solar/dollar-bold-duotone";
import i_double_alt_arrow_left_linear from "@iconify-icons/solar/double-alt-arrow-left-linear";
import i_double_alt_arrow_left_outline from "@iconify-icons/solar/double-alt-arrow-left-outline";
import i_double_alt_arrow_left_bold from "@iconify-icons/solar/double-alt-arrow-left-bold";
import i_double_alt_arrow_left_bold_duotone from "@iconify-icons/solar/double-alt-arrow-left-bold-duotone";
import i_double_alt_arrow_right_linear from "@iconify-icons/solar/double-alt-arrow-right-linear";
import i_double_alt_arrow_right_outline from "@iconify-icons/solar/double-alt-arrow-right-outline";
import i_double_alt_arrow_right_bold from "@iconify-icons/solar/double-alt-arrow-right-bold";
import i_double_alt_arrow_right_bold_duotone from "@iconify-icons/solar/double-alt-arrow-right-bold-duotone";
import i_download_linear from "@iconify-icons/solar/download-linear";
import i_download_outline from "@iconify-icons/solar/download-outline";
import i_download_bold from "@iconify-icons/solar/download-bold";
import i_download_bold_duotone from "@iconify-icons/solar/download-bold-duotone";
import i_download_minimalistic_linear from "@iconify-icons/solar/download-minimalistic-linear";
import i_download_minimalistic_outline from "@iconify-icons/solar/download-minimalistic-outline";
import i_download_minimalistic_bold from "@iconify-icons/solar/download-minimalistic-bold";
import i_download_minimalistic_bold_duotone from "@iconify-icons/solar/download-minimalistic-bold-duotone";
import i_eye_linear from "@iconify-icons/solar/eye-linear";
import i_eye_outline from "@iconify-icons/solar/eye-outline";
import i_eye_bold from "@iconify-icons/solar/eye-bold";
import i_eye_bold_duotone from "@iconify-icons/solar/eye-bold-duotone";
import i_eye_closed_linear from "@iconify-icons/solar/eye-closed-linear";
import i_eye_closed_outline from "@iconify-icons/solar/eye-closed-outline";
import i_eye_closed_bold from "@iconify-icons/solar/eye-closed-bold";
import i_eye_closed_bold_duotone from "@iconify-icons/solar/eye-closed-bold-duotone";
import i_filter_linear from "@iconify-icons/solar/filter-linear";
import i_filter_outline from "@iconify-icons/solar/filter-outline";
import i_filter_bold from "@iconify-icons/solar/filter-bold";
import i_filter_bold_duotone from "@iconify-icons/solar/filter-bold-duotone";
import i_fire_linear from "@iconify-icons/solar/fire-linear";
import i_fire_outline from "@iconify-icons/solar/fire-outline";
import i_fire_bold from "@iconify-icons/solar/fire-bold";
import i_fire_bold_duotone from "@iconify-icons/solar/fire-bold-duotone";
import i_flag_linear from "@iconify-icons/solar/flag-linear";
import i_flag_outline from "@iconify-icons/solar/flag-outline";
import i_flag_bold from "@iconify-icons/solar/flag-bold";
import i_flag_bold_duotone from "@iconify-icons/solar/flag-bold-duotone";
import i_folder_linear from "@iconify-icons/solar/folder-linear";
import i_folder_outline from "@iconify-icons/solar/folder-outline";
import i_folder_bold from "@iconify-icons/solar/folder-bold";
import i_folder_bold_duotone from "@iconify-icons/solar/folder-bold-duotone";
import i_folder_open_linear from "@iconify-icons/solar/folder-open-linear";
import i_folder_open_outline from "@iconify-icons/solar/folder-open-outline";
import i_folder_open_bold from "@iconify-icons/solar/folder-open-bold";
import i_folder_open_bold_duotone from "@iconify-icons/solar/folder-open-bold-duotone";
import i_forbidden_circle_linear from "@iconify-icons/solar/forbidden-circle-linear";
import i_forbidden_circle_outline from "@iconify-icons/solar/forbidden-circle-outline";
import i_forbidden_circle_bold from "@iconify-icons/solar/forbidden-circle-bold";
import i_forbidden_circle_bold_duotone from "@iconify-icons/solar/forbidden-circle-bold-duotone";
import i_full_screen_linear from "@iconify-icons/solar/full-screen-linear";
import i_full_screen_outline from "@iconify-icons/solar/full-screen-outline";
import i_full_screen_bold from "@iconify-icons/solar/full-screen-bold";
import i_full_screen_bold_duotone from "@iconify-icons/solar/full-screen-bold-duotone";
import i_gamepad_linear from "@iconify-icons/solar/gamepad-linear";
import i_gamepad_outline from "@iconify-icons/solar/gamepad-outline";
import i_gamepad_bold from "@iconify-icons/solar/gamepad-bold";
import i_gamepad_bold_duotone from "@iconify-icons/solar/gamepad-bold-duotone";
import i_gift_linear from "@iconify-icons/solar/gift-linear";
import i_gift_outline from "@iconify-icons/solar/gift-outline";
import i_gift_bold from "@iconify-icons/solar/gift-bold";
import i_gift_bold_duotone from "@iconify-icons/solar/gift-bold-duotone";
import i_graph_new_up_linear from "@iconify-icons/solar/graph-new-up-linear";
import i_graph_new_up_outline from "@iconify-icons/solar/graph-new-up-outline";
import i_graph_new_up_bold from "@iconify-icons/solar/graph-new-up-bold";
import i_graph_new_up_bold_duotone from "@iconify-icons/solar/graph-new-up-bold-duotone";
import i_graph_up_linear from "@iconify-icons/solar/graph-up-linear";
import i_graph_up_outline from "@iconify-icons/solar/graph-up-outline";
import i_graph_up_bold from "@iconify-icons/solar/graph-up-bold";
import i_graph_up_bold_duotone from "@iconify-icons/solar/graph-up-bold-duotone";
import i_hamburger_menu_linear from "@iconify-icons/solar/hamburger-menu-linear";
import i_hamburger_menu_outline from "@iconify-icons/solar/hamburger-menu-outline";
import i_hamburger_menu_bold from "@iconify-icons/solar/hamburger-menu-bold";
import i_hamburger_menu_bold_duotone from "@iconify-icons/solar/hamburger-menu-bold-duotone";
import i_hand_stars_linear from "@iconify-icons/solar/hand-stars-linear";
import i_hand_stars_outline from "@iconify-icons/solar/hand-stars-outline";
import i_hand_stars_bold from "@iconify-icons/solar/hand-stars-bold";
import i_hand_stars_bold_duotone from "@iconify-icons/solar/hand-stars-bold-duotone";
import i_heart_linear from "@iconify-icons/solar/heart-linear";
import i_heart_outline from "@iconify-icons/solar/heart-outline";
import i_heart_bold from "@iconify-icons/solar/heart-bold";
import i_heart_bold_duotone from "@iconify-icons/solar/heart-bold-duotone";
import i_heart_broken_linear from "@iconify-icons/solar/heart-broken-linear";
import i_heart_broken_outline from "@iconify-icons/solar/heart-broken-outline";
import i_heart_broken_bold from "@iconify-icons/solar/heart-broken-bold";
import i_heart_broken_bold_duotone from "@iconify-icons/solar/heart-broken-bold-duotone";
import i_history_linear from "@iconify-icons/solar/history-linear";
import i_history_outline from "@iconify-icons/solar/history-outline";
import i_history_bold from "@iconify-icons/solar/history-bold";
import i_history_bold_duotone from "@iconify-icons/solar/history-bold-duotone";
import i_home_2_linear from "@iconify-icons/solar/home-2-linear";
import i_home_2_outline from "@iconify-icons/solar/home-2-outline";
import i_home_2_bold from "@iconify-icons/solar/home-2-bold";
import i_home_2_bold_duotone from "@iconify-icons/solar/home-2-bold-duotone";
import i_home_smile_linear from "@iconify-icons/solar/home-smile-linear";
import i_home_smile_outline from "@iconify-icons/solar/home-smile-outline";
import i_home_smile_bold from "@iconify-icons/solar/home-smile-bold";
import i_home_smile_bold_duotone from "@iconify-icons/solar/home-smile-bold-duotone";
import i_info_circle_linear from "@iconify-icons/solar/info-circle-linear";
import i_info_circle_outline from "@iconify-icons/solar/info-circle-outline";
import i_info_circle_bold from "@iconify-icons/solar/info-circle-bold";
import i_info_circle_bold_duotone from "@iconify-icons/solar/info-circle-bold-duotone";
import i_key_linear from "@iconify-icons/solar/key-linear";
import i_key_outline from "@iconify-icons/solar/key-outline";
import i_key_bold from "@iconify-icons/solar/key-bold";
import i_key_bold_duotone from "@iconify-icons/solar/key-bold-duotone";
import i_keyboard_linear from "@iconify-icons/solar/keyboard-linear";
import i_keyboard_outline from "@iconify-icons/solar/keyboard-outline";
import i_keyboard_bold from "@iconify-icons/solar/keyboard-bold";
import i_keyboard_bold_duotone from "@iconify-icons/solar/keyboard-bold-duotone";
import i_letter_linear from "@iconify-icons/solar/letter-linear";
import i_letter_outline from "@iconify-icons/solar/letter-outline";
import i_letter_bold from "@iconify-icons/solar/letter-bold";
import i_letter_bold_duotone from "@iconify-icons/solar/letter-bold-duotone";
import i_list_linear from "@iconify-icons/solar/list-linear";
import i_list_outline from "@iconify-icons/solar/list-outline";
import i_list_bold from "@iconify-icons/solar/list-bold";
import i_list_bold_duotone from "@iconify-icons/solar/list-bold-duotone";
import i_lock_linear from "@iconify-icons/solar/lock-linear";
import i_lock_outline from "@iconify-icons/solar/lock-outline";
import i_lock_bold from "@iconify-icons/solar/lock-bold";
import i_lock_bold_duotone from "@iconify-icons/solar/lock-bold-duotone";
import i_login_2_linear from "@iconify-icons/solar/login-2-linear";
import i_login_2_outline from "@iconify-icons/solar/login-2-outline";
import i_login_2_bold from "@iconify-icons/solar/login-2-bold";
import i_login_2_bold_duotone from "@iconify-icons/solar/login-2-bold-duotone";
import i_logout_2_linear from "@iconify-icons/solar/logout-2-linear";
import i_logout_2_outline from "@iconify-icons/solar/logout-2-outline";
import i_logout_2_bold from "@iconify-icons/solar/logout-2-bold";
import i_logout_2_bold_duotone from "@iconify-icons/solar/logout-2-bold-duotone";
import i_magnifer_linear from "@iconify-icons/solar/magnifer-linear";
import i_magnifer_outline from "@iconify-icons/solar/magnifer-outline";
import i_magnifer_bold from "@iconify-icons/solar/magnifer-bold";
import i_magnifer_bold_duotone from "@iconify-icons/solar/magnifer-bold-duotone";
import i_menu_dots_linear from "@iconify-icons/solar/menu-dots-linear";
import i_menu_dots_outline from "@iconify-icons/solar/menu-dots-outline";
import i_menu_dots_bold from "@iconify-icons/solar/menu-dots-bold";
import i_menu_dots_bold_duotone from "@iconify-icons/solar/menu-dots-bold-duotone";
import i_menu_dots_vertical_linear from "@iconify-icons/solar/menu-dots-vertical-linear";
import i_menu_dots_vertical_outline from "@iconify-icons/solar/menu-dots-vertical-outline";
import i_menu_dots_vertical_bold from "@iconify-icons/solar/menu-dots-vertical-bold";
import i_menu_dots_vertical_bold_duotone from "@iconify-icons/solar/menu-dots-vertical-bold-duotone";
import i_microphone_linear from "@iconify-icons/solar/microphone-linear";
import i_microphone_outline from "@iconify-icons/solar/microphone-outline";
import i_microphone_bold from "@iconify-icons/solar/microphone-bold";
import i_microphone_bold_duotone from "@iconify-icons/solar/microphone-bold-duotone";
import i_money_bag_linear from "@iconify-icons/solar/money-bag-linear";
import i_money_bag_outline from "@iconify-icons/solar/money-bag-outline";
import i_money_bag_bold from "@iconify-icons/solar/money-bag-bold";
import i_money_bag_bold_duotone from "@iconify-icons/solar/money-bag-bold-duotone";
import i_monitor_linear from "@iconify-icons/solar/monitor-linear";
import i_monitor_outline from "@iconify-icons/solar/monitor-outline";
import i_monitor_bold from "@iconify-icons/solar/monitor-bold";
import i_monitor_bold_duotone from "@iconify-icons/solar/monitor-bold-duotone";
import i_moon_linear from "@iconify-icons/solar/moon-linear";
import i_moon_outline from "@iconify-icons/solar/moon-outline";
import i_moon_bold from "@iconify-icons/solar/moon-bold";
import i_moon_bold_duotone from "@iconify-icons/solar/moon-bold-duotone";
import i_moon_stars_linear from "@iconify-icons/solar/moon-stars-linear";
import i_moon_stars_outline from "@iconify-icons/solar/moon-stars-outline";
import i_moon_stars_bold from "@iconify-icons/solar/moon-stars-bold";
import i_moon_stars_bold_duotone from "@iconify-icons/solar/moon-stars-bold-duotone";
import i_muted_linear from "@iconify-icons/solar/muted-linear";
import i_muted_outline from "@iconify-icons/solar/muted-outline";
import i_muted_bold from "@iconify-icons/solar/muted-bold";
import i_muted_bold_duotone from "@iconify-icons/solar/muted-bold-duotone";
import i_palette_linear from "@iconify-icons/solar/palette-linear";
import i_palette_outline from "@iconify-icons/solar/palette-outline";
import i_palette_bold from "@iconify-icons/solar/palette-bold";
import i_palette_bold_duotone from "@iconify-icons/solar/palette-bold-duotone";
import i_pie_chart_2_linear from "@iconify-icons/solar/pie-chart-2-linear";
import i_pie_chart_2_outline from "@iconify-icons/solar/pie-chart-2-outline";
import i_pie_chart_2_bold from "@iconify-icons/solar/pie-chart-2-bold";
import i_pie_chart_2_bold_duotone from "@iconify-icons/solar/pie-chart-2-bold-duotone";
import i_pin_linear from "@iconify-icons/solar/pin-linear";
import i_pin_outline from "@iconify-icons/solar/pin-outline";
import i_pin_bold from "@iconify-icons/solar/pin-bold";
import i_pin_bold_duotone from "@iconify-icons/solar/pin-bold-duotone";
import i_pip_linear from "@iconify-icons/solar/pip-linear";
import i_pip_outline from "@iconify-icons/solar/pip-outline";
import i_pip_bold from "@iconify-icons/solar/pip-bold";
import i_pip_bold_duotone from "@iconify-icons/solar/pip-bold-duotone";
import i_plain_2_linear from "@iconify-icons/solar/plain-2-linear";
import i_plain_2_outline from "@iconify-icons/solar/plain-2-outline";
import i_plain_2_bold from "@iconify-icons/solar/plain-2-bold";
import i_plain_2_bold_duotone from "@iconify-icons/solar/plain-2-bold-duotone";
import i_play_linear from "@iconify-icons/solar/play-linear";
import i_play_outline from "@iconify-icons/solar/play-outline";
import i_play_bold from "@iconify-icons/solar/play-bold";
import i_play_bold_duotone from "@iconify-icons/solar/play-bold-duotone";
import i_play_circle_linear from "@iconify-icons/solar/play-circle-linear";
import i_play_circle_outline from "@iconify-icons/solar/play-circle-outline";
import i_play_circle_bold from "@iconify-icons/solar/play-circle-bold";
import i_play_circle_bold_duotone from "@iconify-icons/solar/play-circle-bold-duotone";
import i_play_stream_linear from "@iconify-icons/solar/play-stream-linear";
import i_play_stream_outline from "@iconify-icons/solar/play-stream-outline";
import i_play_stream_bold from "@iconify-icons/solar/play-stream-bold";
import i_play_stream_bold_duotone from "@iconify-icons/solar/play-stream-bold-duotone";
import i_pulse_linear from "@iconify-icons/solar/pulse-linear";
import i_pulse_outline from "@iconify-icons/solar/pulse-outline";
import i_pulse_bold from "@iconify-icons/solar/pulse-bold";
import i_pulse_bold_duotone from "@iconify-icons/solar/pulse-bold-duotone";
import i_question_circle_linear from "@iconify-icons/solar/question-circle-linear";
import i_question_circle_outline from "@iconify-icons/solar/question-circle-outline";
import i_question_circle_bold from "@iconify-icons/solar/question-circle-bold";
import i_question_circle_bold_duotone from "@iconify-icons/solar/question-circle-bold-duotone";
import i_refresh_linear from "@iconify-icons/solar/refresh-linear";
import i_refresh_outline from "@iconify-icons/solar/refresh-outline";
import i_refresh_bold from "@iconify-icons/solar/refresh-bold";
import i_refresh_bold_duotone from "@iconify-icons/solar/refresh-bold-duotone";
import i_screen_share_linear from "@iconify-icons/solar/screen-share-linear";
import i_screen_share_outline from "@iconify-icons/solar/screen-share-outline";
import i_screen_share_bold from "@iconify-icons/solar/screen-share-bold";
import i_screen_share_bold_duotone from "@iconify-icons/solar/screen-share-bold-duotone";
import i_settings_linear from "@iconify-icons/solar/settings-linear";
import i_settings_outline from "@iconify-icons/solar/settings-outline";
import i_settings_bold from "@iconify-icons/solar/settings-bold";
import i_settings_bold_duotone from "@iconify-icons/solar/settings-bold-duotone";
import i_share_linear from "@iconify-icons/solar/share-linear";
import i_share_outline from "@iconify-icons/solar/share-outline";
import i_share_bold from "@iconify-icons/solar/share-bold";
import i_share_bold_duotone from "@iconify-icons/solar/share-bold-duotone";
import i_share_circle_linear from "@iconify-icons/solar/share-circle-linear";
import i_share_circle_outline from "@iconify-icons/solar/share-circle-outline";
import i_share_circle_bold from "@iconify-icons/solar/share-circle-bold";
import i_share_circle_bold_duotone from "@iconify-icons/solar/share-circle-bold-duotone";
import i_shield_linear from "@iconify-icons/solar/shield-linear";
import i_shield_outline from "@iconify-icons/solar/shield-outline";
import i_shield_bold from "@iconify-icons/solar/shield-bold";
import i_shield_bold_duotone from "@iconify-icons/solar/shield-bold-duotone";
import i_shield_star_linear from "@iconify-icons/solar/shield-star-linear";
import i_shield_star_outline from "@iconify-icons/solar/shield-star-outline";
import i_shield_star_bold from "@iconify-icons/solar/shield-star-bold";
import i_shield_star_bold_duotone from "@iconify-icons/solar/shield-star-bold-duotone";
import i_shop_linear from "@iconify-icons/solar/shop-linear";
import i_shop_outline from "@iconify-icons/solar/shop-outline";
import i_shop_bold from "@iconify-icons/solar/shop-bold";
import i_shop_bold_duotone from "@iconify-icons/solar/shop-bold-duotone";
import i_sidebar_linear from "@iconify-icons/solar/sidebar-linear";
import i_sidebar_outline from "@iconify-icons/solar/sidebar-outline";
import i_sidebar_bold from "@iconify-icons/solar/sidebar-bold";
import i_sidebar_bold_duotone from "@iconify-icons/solar/sidebar-bold-duotone";
import i_smile_circle_linear from "@iconify-icons/solar/smile-circle-linear";
import i_smile_circle_outline from "@iconify-icons/solar/smile-circle-outline";
import i_smile_circle_bold from "@iconify-icons/solar/smile-circle-bold";
import i_smile_circle_bold_duotone from "@iconify-icons/solar/smile-circle-bold-duotone";
import i_square_academic_cap_linear from "@iconify-icons/solar/square-academic-cap-linear";
import i_square_academic_cap_outline from "@iconify-icons/solar/square-academic-cap-outline";
import i_square_academic_cap_bold from "@iconify-icons/solar/square-academic-cap-bold";
import i_square_academic_cap_bold_duotone from "@iconify-icons/solar/square-academic-cap-bold-duotone";
import i_square_arrow_right_up_linear from "@iconify-icons/solar/square-arrow-right-up-linear";
import i_square_arrow_right_up_outline from "@iconify-icons/solar/square-arrow-right-up-outline";
import i_square_arrow_right_up_bold from "@iconify-icons/solar/square-arrow-right-up-bold";
import i_square_arrow_right_up_bold_duotone from "@iconify-icons/solar/square-arrow-right-up-bold-duotone";
import i_stars_linear from "@iconify-icons/solar/stars-linear";
import i_stars_outline from "@iconify-icons/solar/stars-outline";
import i_stars_bold from "@iconify-icons/solar/stars-bold";
import i_stars_bold_duotone from "@iconify-icons/solar/stars-bold-duotone";
import i_stop_linear from "@iconify-icons/solar/stop-linear";
import i_stop_outline from "@iconify-icons/solar/stop-outline";
import i_stop_bold from "@iconify-icons/solar/stop-bold";
import i_stop_bold_duotone from "@iconify-icons/solar/stop-bold-duotone";
import i_stopwatch_linear from "@iconify-icons/solar/stopwatch-linear";
import i_stopwatch_outline from "@iconify-icons/solar/stopwatch-outline";
import i_stopwatch_bold from "@iconify-icons/solar/stopwatch-bold";
import i_stopwatch_bold_duotone from "@iconify-icons/solar/stopwatch-bold-duotone";
import i_sun_linear from "@iconify-icons/solar/sun-linear";
import i_sun_outline from "@iconify-icons/solar/sun-outline";
import i_sun_bold from "@iconify-icons/solar/sun-bold";
import i_sun_bold_duotone from "@iconify-icons/solar/sun-bold-duotone";
import i_tag_linear from "@iconify-icons/solar/tag-linear";
import i_tag_outline from "@iconify-icons/solar/tag-outline";
import i_tag_bold from "@iconify-icons/solar/tag-bold";
import i_tag_bold_duotone from "@iconify-icons/solar/tag-bold-duotone";
import i_target_linear from "@iconify-icons/solar/target-linear";
import i_target_outline from "@iconify-icons/solar/target-outline";
import i_target_bold from "@iconify-icons/solar/target-bold";
import i_target_bold_duotone from "@iconify-icons/solar/target-bold-duotone";
import i_ticket_linear from "@iconify-icons/solar/ticket-linear";
import i_ticket_outline from "@iconify-icons/solar/ticket-outline";
import i_ticket_bold from "@iconify-icons/solar/ticket-bold";
import i_ticket_bold_duotone from "@iconify-icons/solar/ticket-bold-duotone";
import i_translation_linear from "@iconify-icons/solar/translation-linear";
import i_translation_outline from "@iconify-icons/solar/translation-outline";
import i_translation_bold from "@iconify-icons/solar/translation-bold";
import i_translation_bold_duotone from "@iconify-icons/solar/translation-bold-duotone";
import i_trash_bin_trash_linear from "@iconify-icons/solar/trash-bin-trash-linear";
import i_trash_bin_trash_outline from "@iconify-icons/solar/trash-bin-trash-outline";
import i_trash_bin_trash_bold from "@iconify-icons/solar/trash-bin-trash-bold";
import i_trash_bin_trash_bold_duotone from "@iconify-icons/solar/trash-bin-trash-bold-duotone";
import i_tuning_2_linear from "@iconify-icons/solar/tuning-2-linear";
import i_tuning_2_outline from "@iconify-icons/solar/tuning-2-outline";
import i_tuning_2_bold from "@iconify-icons/solar/tuning-2-bold";
import i_tuning_2_bold_duotone from "@iconify-icons/solar/tuning-2-bold-duotone";
import i_tv_linear from "@iconify-icons/solar/tv-linear";
import i_tv_outline from "@iconify-icons/solar/tv-outline";
import i_tv_bold from "@iconify-icons/solar/tv-bold";
import i_tv_bold_duotone from "@iconify-icons/solar/tv-bold-duotone";
import i_user_plus_rounded_linear from "@iconify-icons/solar/user-plus-rounded-linear";
import i_user_plus_rounded_outline from "@iconify-icons/solar/user-plus-rounded-outline";
import i_user_plus_rounded_bold from "@iconify-icons/solar/user-plus-rounded-bold";
import i_user_plus_rounded_bold_duotone from "@iconify-icons/solar/user-plus-rounded-bold-duotone";
import i_user_rounded_linear from "@iconify-icons/solar/user-rounded-linear";
import i_user_rounded_outline from "@iconify-icons/solar/user-rounded-outline";
import i_user_rounded_bold from "@iconify-icons/solar/user-rounded-bold";
import i_user_rounded_bold_duotone from "@iconify-icons/solar/user-rounded-bold-duotone";
import i_users_group_rounded_linear from "@iconify-icons/solar/users-group-rounded-linear";
import i_users_group_rounded_outline from "@iconify-icons/solar/users-group-rounded-outline";
import i_users_group_rounded_bold from "@iconify-icons/solar/users-group-rounded-bold";
import i_users_group_rounded_bold_duotone from "@iconify-icons/solar/users-group-rounded-bold-duotone";
import i_users_group_two_rounded_linear from "@iconify-icons/solar/users-group-two-rounded-linear";
import i_users_group_two_rounded_outline from "@iconify-icons/solar/users-group-two-rounded-outline";
import i_users_group_two_rounded_bold from "@iconify-icons/solar/users-group-two-rounded-bold";
import i_users_group_two_rounded_bold_duotone from "@iconify-icons/solar/users-group-two-rounded-bold-duotone";
import i_verified_check_linear from "@iconify-icons/solar/verified-check-linear";
import i_verified_check_outline from "@iconify-icons/solar/verified-check-outline";
import i_verified_check_bold from "@iconify-icons/solar/verified-check-bold";
import i_verified_check_bold_duotone from "@iconify-icons/solar/verified-check-bold-duotone";
import i_videocamera_linear from "@iconify-icons/solar/videocamera-linear";
import i_videocamera_outline from "@iconify-icons/solar/videocamera-outline";
import i_videocamera_bold from "@iconify-icons/solar/videocamera-bold";
import i_videocamera_bold_duotone from "@iconify-icons/solar/videocamera-bold-duotone";
import i_videocamera_off_linear from "@iconify-icons/solar/videocamera-off-linear";
import i_videocamera_off_outline from "@iconify-icons/solar/videocamera-off-outline";
import i_videocamera_off_bold from "@iconify-icons/solar/videocamera-off-bold";
import i_videocamera_off_bold_duotone from "@iconify-icons/solar/videocamera-off-bold-duotone";
import i_volume_cross_linear from "@iconify-icons/solar/volume-cross-linear";
import i_volume_cross_outline from "@iconify-icons/solar/volume-cross-outline";
import i_volume_cross_bold from "@iconify-icons/solar/volume-cross-bold";
import i_volume_cross_bold_duotone from "@iconify-icons/solar/volume-cross-bold-duotone";
import i_volume_loud_linear from "@iconify-icons/solar/volume-loud-linear";
import i_volume_loud_outline from "@iconify-icons/solar/volume-loud-outline";
import i_volume_loud_bold from "@iconify-icons/solar/volume-loud-bold";
import i_volume_loud_bold_duotone from "@iconify-icons/solar/volume-loud-bold-duotone";
import i_wallet_linear from "@iconify-icons/solar/wallet-linear";
import i_wallet_outline from "@iconify-icons/solar/wallet-outline";
import i_wallet_bold from "@iconify-icons/solar/wallet-bold";
import i_wallet_bold_duotone from "@iconify-icons/solar/wallet-bold-duotone";
import i_wallet_money_linear from "@iconify-icons/solar/wallet-money-linear";
import i_wallet_money_outline from "@iconify-icons/solar/wallet-money-outline";
import i_wallet_money_bold from "@iconify-icons/solar/wallet-money-bold";
import i_wallet_money_bold_duotone from "@iconify-icons/solar/wallet-money-bold-duotone";
import i_wi_fi_router_minimalistic_linear from "@iconify-icons/solar/wi-fi-router-minimalistic-linear";
import i_wi_fi_router_minimalistic_outline from "@iconify-icons/solar/wi-fi-router-minimalistic-outline";
import i_wi_fi_router_minimalistic_bold from "@iconify-icons/solar/wi-fi-router-minimalistic-bold";
import i_wi_fi_router_minimalistic_bold_duotone from "@iconify-icons/solar/wi-fi-router-minimalistic-bold-duotone";
import i_widget_4_linear from "@iconify-icons/solar/widget-4-linear";
import i_widget_4_outline from "@iconify-icons/solar/widget-4-outline";
import i_widget_4_bold from "@iconify-icons/solar/widget-4-bold";
import i_widget_4_bold_duotone from "@iconify-icons/solar/widget-4-bold-duotone";
import i_sidebar_minimalistic_linear from "@iconify-icons/solar/sidebar-minimalistic-linear";
import i_sidebar_minimalistic_outline from "@iconify-icons/solar/sidebar-minimalistic-outline";
import i_sidebar_minimalistic_bold from "@iconify-icons/solar/sidebar-minimalistic-bold";
import i_sidebar_minimalistic_bold_duotone from "@iconify-icons/solar/sidebar-minimalistic-bold-duotone";
import i_gallery_add_linear from "@iconify-icons/solar/gallery-add-linear";
import i_gallery_add_outline from "@iconify-icons/solar/gallery-add-outline";
import i_gallery_add_bold from "@iconify-icons/solar/gallery-add-bold";
import i_gallery_add_bold_duotone from "@iconify-icons/solar/gallery-add-bold-duotone";
import i_gallery_edit_linear from "@iconify-icons/solar/gallery-edit-linear";
import i_gallery_edit_outline from "@iconify-icons/solar/gallery-edit-outline";
import i_gallery_edit_bold from "@iconify-icons/solar/gallery-edit-bold";
import i_gallery_edit_bold_duotone from "@iconify-icons/solar/gallery-edit-bold-duotone";

type IconData = { body: string; width?: number; height?: number };
type Set = { linear: IconData; outline: IconData; bold: IconData; duotone: IconData };

export type IconWeight = "thin" | "light" | "regular" | "bold" | "fill" | "duotone";
export interface IconProps extends Omit<SVGProps<SVGSVGElement>, "ref"> {
  size?: number | string;
  weight?: IconWeight;
  color?: string;
  mirrored?: boolean;
}
export type Icon = (props: IconProps) => React.JSX.Element;

function pick(set: Set, weight: IconWeight): IconData {
  if (weight === "fill") return set.bold;
  if (weight === "duotone") return set.duotone;
  if (weight === "bold") return set.outline;
  return set.linear;
}

function make(set: Set): Icon {
  const Cmp = ({ size = "1em", weight = "regular", color = "currentColor", mirrored, className, style, ...rest }: IconProps) => {
    const d = pick(set, weight);
    const st: CSSProperties | undefined = mirrored ? { ...style, transform: "scaleX(-1)" } : style;
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox={`0 0 ${d.width ?? 24} ${d.height ?? 24}`}
        color={color}
        className={className}
        style={st}
        aria-hidden={rest["aria-label"] ? undefined : true}
        {...rest}
        dangerouslySetInnerHTML={{ __html: d.body }}
      />
    );
  };
  return Cmp;
}

function drawn(linear: string, bold: string): Set {
  return { linear: { body: linear }, outline: { body: bold }, bold: { body: bold }, duotone: { body: bold } };
}

const S_i_add = { linear: i_add_linear, outline: i_add_outline, bold: i_add_bold, duotone: i_add_bold_duotone };
const S_i_alt_arrow_down = { linear: i_alt_arrow_down_linear, outline: i_alt_arrow_down_outline, bold: i_alt_arrow_down_bold, duotone: i_alt_arrow_down_bold_duotone };
const S_i_alt_arrow_left = { linear: i_alt_arrow_left_linear, outline: i_alt_arrow_left_outline, bold: i_alt_arrow_left_bold, duotone: i_alt_arrow_left_bold_duotone };
const S_i_alt_arrow_right = { linear: i_alt_arrow_right_linear, outline: i_alt_arrow_right_outline, bold: i_alt_arrow_right_bold, duotone: i_alt_arrow_right_bold_duotone };
const S_i_alt_arrow_up = { linear: i_alt_arrow_up_linear, outline: i_alt_arrow_up_outline, bold: i_alt_arrow_up_bold, duotone: i_alt_arrow_up_bold_duotone };
const S_i_arrow_down = { linear: i_arrow_down_linear, outline: i_arrow_down_outline, bold: i_arrow_down_bold, duotone: i_arrow_down_bold_duotone };
const S_i_arrow_left = { linear: i_arrow_left_linear, outline: i_arrow_left_outline, bold: i_arrow_left_bold, duotone: i_arrow_left_bold_duotone };
const S_i_arrow_right = { linear: i_arrow_right_linear, outline: i_arrow_right_outline, bold: i_arrow_right_bold, duotone: i_arrow_right_bold_duotone };
const S_i_arrow_right_up = { linear: i_arrow_right_up_linear, outline: i_arrow_right_up_outline, bold: i_arrow_right_up_bold, duotone: i_arrow_right_up_bold_duotone };
const S_i_arrow_up = { linear: i_arrow_up_linear, outline: i_arrow_up_outline, bold: i_arrow_up_bold, duotone: i_arrow_up_bold_duotone };
const S_i_bell = { linear: i_bell_linear, outline: i_bell_outline, bold: i_bell_bold, duotone: i_bell_bold_duotone };
const S_i_bell_bing = { linear: i_bell_bing_linear, outline: i_bell_bing_outline, bold: i_bell_bing_bold, duotone: i_bell_bing_bold_duotone };
const S_i_bill_list = { linear: i_bill_list_linear, outline: i_bill_list_outline, bold: i_bill_list_bold, duotone: i_bill_list_bold_duotone };
const S_i_bluetooth = { linear: i_bluetooth_linear, outline: i_bluetooth_outline, bold: i_bluetooth_bold, duotone: i_bluetooth_bold_duotone };
const S_i_bolt = { linear: i_bolt_linear, outline: i_bolt_outline, bold: i_bolt_bold, duotone: i_bolt_bold_duotone };
const S_i_bolt_circle = { linear: i_bolt_circle_linear, outline: i_bolt_circle_outline, bold: i_bolt_circle_bold, duotone: i_bolt_circle_bold_duotone };
const S_i_calendar_add = { linear: i_calendar_add_linear, outline: i_calendar_add_outline, bold: i_calendar_add_bold, duotone: i_calendar_add_bold_duotone };
const S_i_calendar_minimalistic = { linear: i_calendar_minimalistic_linear, outline: i_calendar_minimalistic_outline, bold: i_calendar_minimalistic_bold, duotone: i_calendar_minimalistic_bold_duotone };
const S_i_camera = { linear: i_camera_linear, outline: i_camera_outline, bold: i_camera_bold, duotone: i_camera_bold_duotone };
const S_i_camera_rotate = { linear: i_camera_rotate_linear, outline: i_camera_rotate_outline, bold: i_camera_rotate_bold, duotone: i_camera_rotate_bold_duotone };
const S_i_card = { linear: i_card_linear, outline: i_card_outline, bold: i_card_bold, duotone: i_card_bold_duotone };
const S_i_chart_2 = { linear: i_chart_2_linear, outline: i_chart_2_outline, bold: i_chart_2_bold, duotone: i_chart_2_bold_duotone };
const S_i_chat_line = { linear: i_chat_line_linear, outline: i_chat_line_outline, bold: i_chat_line_bold, duotone: i_chat_line_bold_duotone };
const S_i_chat_round = { linear: i_chat_round_linear, outline: i_chat_round_outline, bold: i_chat_round_bold, duotone: i_chat_round_bold_duotone };
const S_i_chat_round_dots = { linear: i_chat_round_dots_linear, outline: i_chat_round_dots_outline, bold: i_chat_round_dots_bold, duotone: i_chat_round_dots_bold_duotone };
const S_i_check_circle = { linear: i_check_circle_linear, outline: i_check_circle_outline, bold: i_check_circle_bold, duotone: i_check_circle_bold_duotone };
const S_i_check_read = { linear: i_check_read_linear, outline: i_check_read_outline, bold: i_check_read_bold, duotone: i_check_read_bold_duotone };
const S_i_clock_circle = { linear: i_clock_circle_linear, outline: i_clock_circle_outline, bold: i_clock_circle_bold, duotone: i_clock_circle_bold_duotone };
const S_i_code_2 = { linear: i_code_2_linear, outline: i_code_2_outline, bold: i_code_2_bold, duotone: i_code_2_bold_duotone };
const S_i_compass = { linear: i_compass_linear, outline: i_compass_outline, bold: i_compass_bold, duotone: i_compass_bold_duotone };
const S_i_copy = { linear: i_copy_linear, outline: i_copy_outline, bold: i_copy_bold, duotone: i_copy_bold_duotone };
const S_i_crown = { linear: i_crown_linear, outline: i_crown_outline, bold: i_crown_bold, duotone: i_crown_bold_duotone };
const S_i_cup_star = { linear: i_cup_star_linear, outline: i_cup_star_outline, bold: i_cup_star_bold, duotone: i_cup_star_bold_duotone };
const S_i_danger_circle = { linear: i_danger_circle_linear, outline: i_danger_circle_outline, bold: i_danger_circle_bold, duotone: i_danger_circle_bold_duotone };
const S_i_danger_triangle = { linear: i_danger_triangle_linear, outline: i_danger_triangle_outline, bold: i_danger_triangle_bold, duotone: i_danger_triangle_bold_duotone };
const S_i_diskette = { linear: i_diskette_linear, outline: i_diskette_outline, bold: i_diskette_bold, duotone: i_diskette_bold_duotone };
const S_i_document = { linear: i_document_linear, outline: i_document_outline, bold: i_document_bold, duotone: i_document_bold_duotone };
const S_i_document_text = { linear: i_document_text_linear, outline: i_document_text_outline, bold: i_document_text_bold, duotone: i_document_text_bold_duotone };
const S_i_dollar = { linear: i_dollar_linear, outline: i_dollar_outline, bold: i_dollar_bold, duotone: i_dollar_bold_duotone };
const S_i_double_alt_arrow_left = { linear: i_double_alt_arrow_left_linear, outline: i_double_alt_arrow_left_outline, bold: i_double_alt_arrow_left_bold, duotone: i_double_alt_arrow_left_bold_duotone };
const S_i_double_alt_arrow_right = { linear: i_double_alt_arrow_right_linear, outline: i_double_alt_arrow_right_outline, bold: i_double_alt_arrow_right_bold, duotone: i_double_alt_arrow_right_bold_duotone };
const S_i_download = { linear: i_download_linear, outline: i_download_outline, bold: i_download_bold, duotone: i_download_bold_duotone };
const S_i_download_minimalistic = { linear: i_download_minimalistic_linear, outline: i_download_minimalistic_outline, bold: i_download_minimalistic_bold, duotone: i_download_minimalistic_bold_duotone };
const S_i_eye = { linear: i_eye_linear, outline: i_eye_outline, bold: i_eye_bold, duotone: i_eye_bold_duotone };
const S_i_eye_closed = { linear: i_eye_closed_linear, outline: i_eye_closed_outline, bold: i_eye_closed_bold, duotone: i_eye_closed_bold_duotone };
const S_i_filter = { linear: i_filter_linear, outline: i_filter_outline, bold: i_filter_bold, duotone: i_filter_bold_duotone };
const S_i_fire = { linear: i_fire_linear, outline: i_fire_outline, bold: i_fire_bold, duotone: i_fire_bold_duotone };
const S_i_flag = { linear: i_flag_linear, outline: i_flag_outline, bold: i_flag_bold, duotone: i_flag_bold_duotone };
const S_i_folder = { linear: i_folder_linear, outline: i_folder_outline, bold: i_folder_bold, duotone: i_folder_bold_duotone };
const S_i_folder_open = { linear: i_folder_open_linear, outline: i_folder_open_outline, bold: i_folder_open_bold, duotone: i_folder_open_bold_duotone };
const S_i_forbidden_circle = { linear: i_forbidden_circle_linear, outline: i_forbidden_circle_outline, bold: i_forbidden_circle_bold, duotone: i_forbidden_circle_bold_duotone };
const S_i_full_screen = { linear: i_full_screen_linear, outline: i_full_screen_outline, bold: i_full_screen_bold, duotone: i_full_screen_bold_duotone };
const S_i_gamepad = { linear: i_gamepad_linear, outline: i_gamepad_outline, bold: i_gamepad_bold, duotone: i_gamepad_bold_duotone };
const S_i_gift = { linear: i_gift_linear, outline: i_gift_outline, bold: i_gift_bold, duotone: i_gift_bold_duotone };
const S_i_graph_new_up = { linear: i_graph_new_up_linear, outline: i_graph_new_up_outline, bold: i_graph_new_up_bold, duotone: i_graph_new_up_bold_duotone };
const S_i_graph_up = { linear: i_graph_up_linear, outline: i_graph_up_outline, bold: i_graph_up_bold, duotone: i_graph_up_bold_duotone };
const S_i_hamburger_menu = { linear: i_hamburger_menu_linear, outline: i_hamburger_menu_outline, bold: i_hamburger_menu_bold, duotone: i_hamburger_menu_bold_duotone };
const S_i_hand_stars = { linear: i_hand_stars_linear, outline: i_hand_stars_outline, bold: i_hand_stars_bold, duotone: i_hand_stars_bold_duotone };
const S_i_heart = { linear: i_heart_linear, outline: i_heart_outline, bold: i_heart_bold, duotone: i_heart_bold_duotone };
const S_i_heart_broken = { linear: i_heart_broken_linear, outline: i_heart_broken_outline, bold: i_heart_broken_bold, duotone: i_heart_broken_bold_duotone };
const S_i_history = { linear: i_history_linear, outline: i_history_outline, bold: i_history_bold, duotone: i_history_bold_duotone };
const S_i_home_2 = { linear: i_home_2_linear, outline: i_home_2_outline, bold: i_home_2_bold, duotone: i_home_2_bold_duotone };
const S_i_home_smile = { linear: i_home_smile_linear, outline: i_home_smile_outline, bold: i_home_smile_bold, duotone: i_home_smile_bold_duotone };
const S_i_info_circle = { linear: i_info_circle_linear, outline: i_info_circle_outline, bold: i_info_circle_bold, duotone: i_info_circle_bold_duotone };
const S_i_key = { linear: i_key_linear, outline: i_key_outline, bold: i_key_bold, duotone: i_key_bold_duotone };
const S_i_keyboard = { linear: i_keyboard_linear, outline: i_keyboard_outline, bold: i_keyboard_bold, duotone: i_keyboard_bold_duotone };
const S_i_letter = { linear: i_letter_linear, outline: i_letter_outline, bold: i_letter_bold, duotone: i_letter_bold_duotone };
const S_i_list = { linear: i_list_linear, outline: i_list_outline, bold: i_list_bold, duotone: i_list_bold_duotone };
const S_i_lock = { linear: i_lock_linear, outline: i_lock_outline, bold: i_lock_bold, duotone: i_lock_bold_duotone };
const S_i_login_2 = { linear: i_login_2_linear, outline: i_login_2_outline, bold: i_login_2_bold, duotone: i_login_2_bold_duotone };
const S_i_logout_2 = { linear: i_logout_2_linear, outline: i_logout_2_outline, bold: i_logout_2_bold, duotone: i_logout_2_bold_duotone };
const S_i_magnifer = { linear: i_magnifer_linear, outline: i_magnifer_outline, bold: i_magnifer_bold, duotone: i_magnifer_bold_duotone };
const S_i_menu_dots = { linear: i_menu_dots_linear, outline: i_menu_dots_outline, bold: i_menu_dots_bold, duotone: i_menu_dots_bold_duotone };
const S_i_menu_dots_vertical = { linear: i_menu_dots_vertical_linear, outline: i_menu_dots_vertical_outline, bold: i_menu_dots_vertical_bold, duotone: i_menu_dots_vertical_bold_duotone };
const S_i_microphone = { linear: i_microphone_linear, outline: i_microphone_outline, bold: i_microphone_bold, duotone: i_microphone_bold_duotone };
const S_i_money_bag = { linear: i_money_bag_linear, outline: i_money_bag_outline, bold: i_money_bag_bold, duotone: i_money_bag_bold_duotone };
const S_i_monitor = { linear: i_monitor_linear, outline: i_monitor_outline, bold: i_monitor_bold, duotone: i_monitor_bold_duotone };
const S_i_moon = { linear: i_moon_linear, outline: i_moon_outline, bold: i_moon_bold, duotone: i_moon_bold_duotone };
const S_i_moon_stars = { linear: i_moon_stars_linear, outline: i_moon_stars_outline, bold: i_moon_stars_bold, duotone: i_moon_stars_bold_duotone };
const S_i_muted = { linear: i_muted_linear, outline: i_muted_outline, bold: i_muted_bold, duotone: i_muted_bold_duotone };
const S_i_palette = { linear: i_palette_linear, outline: i_palette_outline, bold: i_palette_bold, duotone: i_palette_bold_duotone };
const S_i_pie_chart_2 = { linear: i_pie_chart_2_linear, outline: i_pie_chart_2_outline, bold: i_pie_chart_2_bold, duotone: i_pie_chart_2_bold_duotone };
const S_i_pin = { linear: i_pin_linear, outline: i_pin_outline, bold: i_pin_bold, duotone: i_pin_bold_duotone };
const S_i_pip = { linear: i_pip_linear, outline: i_pip_outline, bold: i_pip_bold, duotone: i_pip_bold_duotone };
const S_i_plain_2 = { linear: i_plain_2_linear, outline: i_plain_2_outline, bold: i_plain_2_bold, duotone: i_plain_2_bold_duotone };
const S_i_play = { linear: i_play_linear, outline: i_play_outline, bold: i_play_bold, duotone: i_play_bold_duotone };
const S_i_play_circle = { linear: i_play_circle_linear, outline: i_play_circle_outline, bold: i_play_circle_bold, duotone: i_play_circle_bold_duotone };
const S_i_play_stream = { linear: i_play_stream_linear, outline: i_play_stream_outline, bold: i_play_stream_bold, duotone: i_play_stream_bold_duotone };
const S_i_pulse = { linear: i_pulse_linear, outline: i_pulse_outline, bold: i_pulse_bold, duotone: i_pulse_bold_duotone };
const S_i_question_circle = { linear: i_question_circle_linear, outline: i_question_circle_outline, bold: i_question_circle_bold, duotone: i_question_circle_bold_duotone };
const S_i_refresh = { linear: i_refresh_linear, outline: i_refresh_outline, bold: i_refresh_bold, duotone: i_refresh_bold_duotone };
const S_i_screen_share = { linear: i_screen_share_linear, outline: i_screen_share_outline, bold: i_screen_share_bold, duotone: i_screen_share_bold_duotone };
const S_i_settings = { linear: i_settings_linear, outline: i_settings_outline, bold: i_settings_bold, duotone: i_settings_bold_duotone };
const S_i_share = { linear: i_share_linear, outline: i_share_outline, bold: i_share_bold, duotone: i_share_bold_duotone };
const S_i_share_circle = { linear: i_share_circle_linear, outline: i_share_circle_outline, bold: i_share_circle_bold, duotone: i_share_circle_bold_duotone };
const S_i_shield = { linear: i_shield_linear, outline: i_shield_outline, bold: i_shield_bold, duotone: i_shield_bold_duotone };
const S_i_shield_star = { linear: i_shield_star_linear, outline: i_shield_star_outline, bold: i_shield_star_bold, duotone: i_shield_star_bold_duotone };
const S_i_shop = { linear: i_shop_linear, outline: i_shop_outline, bold: i_shop_bold, duotone: i_shop_bold_duotone };
const S_i_sidebar = { linear: i_sidebar_linear, outline: i_sidebar_outline, bold: i_sidebar_bold, duotone: i_sidebar_bold_duotone };
const S_i_smile_circle = { linear: i_smile_circle_linear, outline: i_smile_circle_outline, bold: i_smile_circle_bold, duotone: i_smile_circle_bold_duotone };
const S_i_square_academic_cap = { linear: i_square_academic_cap_linear, outline: i_square_academic_cap_outline, bold: i_square_academic_cap_bold, duotone: i_square_academic_cap_bold_duotone };
const S_i_square_arrow_right_up = { linear: i_square_arrow_right_up_linear, outline: i_square_arrow_right_up_outline, bold: i_square_arrow_right_up_bold, duotone: i_square_arrow_right_up_bold_duotone };
const S_i_stars = { linear: i_stars_linear, outline: i_stars_outline, bold: i_stars_bold, duotone: i_stars_bold_duotone };
const S_i_stop = { linear: i_stop_linear, outline: i_stop_outline, bold: i_stop_bold, duotone: i_stop_bold_duotone };
const S_i_stopwatch = { linear: i_stopwatch_linear, outline: i_stopwatch_outline, bold: i_stopwatch_bold, duotone: i_stopwatch_bold_duotone };
const S_i_sun = { linear: i_sun_linear, outline: i_sun_outline, bold: i_sun_bold, duotone: i_sun_bold_duotone };
const S_i_tag = { linear: i_tag_linear, outline: i_tag_outline, bold: i_tag_bold, duotone: i_tag_bold_duotone };
const S_i_target = { linear: i_target_linear, outline: i_target_outline, bold: i_target_bold, duotone: i_target_bold_duotone };
const S_i_ticket = { linear: i_ticket_linear, outline: i_ticket_outline, bold: i_ticket_bold, duotone: i_ticket_bold_duotone };
const S_i_translation = { linear: i_translation_linear, outline: i_translation_outline, bold: i_translation_bold, duotone: i_translation_bold_duotone };
const S_i_trash_bin_trash = { linear: i_trash_bin_trash_linear, outline: i_trash_bin_trash_outline, bold: i_trash_bin_trash_bold, duotone: i_trash_bin_trash_bold_duotone };
const S_i_tuning_2 = { linear: i_tuning_2_linear, outline: i_tuning_2_outline, bold: i_tuning_2_bold, duotone: i_tuning_2_bold_duotone };
const S_i_tv = { linear: i_tv_linear, outline: i_tv_outline, bold: i_tv_bold, duotone: i_tv_bold_duotone };
const S_i_user_plus_rounded = { linear: i_user_plus_rounded_linear, outline: i_user_plus_rounded_outline, bold: i_user_plus_rounded_bold, duotone: i_user_plus_rounded_bold_duotone };
const S_i_user_rounded = { linear: i_user_rounded_linear, outline: i_user_rounded_outline, bold: i_user_rounded_bold, duotone: i_user_rounded_bold_duotone };
const S_i_users_group_rounded = { linear: i_users_group_rounded_linear, outline: i_users_group_rounded_outline, bold: i_users_group_rounded_bold, duotone: i_users_group_rounded_bold_duotone };
const S_i_users_group_two_rounded = { linear: i_users_group_two_rounded_linear, outline: i_users_group_two_rounded_outline, bold: i_users_group_two_rounded_bold, duotone: i_users_group_two_rounded_bold_duotone };
const S_i_verified_check = { linear: i_verified_check_linear, outline: i_verified_check_outline, bold: i_verified_check_bold, duotone: i_verified_check_bold_duotone };
const S_i_videocamera = { linear: i_videocamera_linear, outline: i_videocamera_outline, bold: i_videocamera_bold, duotone: i_videocamera_bold_duotone };
const S_i_videocamera_off = { linear: i_videocamera_off_linear, outline: i_videocamera_off_outline, bold: i_videocamera_off_bold, duotone: i_videocamera_off_bold_duotone };
const S_i_volume_cross = { linear: i_volume_cross_linear, outline: i_volume_cross_outline, bold: i_volume_cross_bold, duotone: i_volume_cross_bold_duotone };
const S_i_volume_loud = { linear: i_volume_loud_linear, outline: i_volume_loud_outline, bold: i_volume_loud_bold, duotone: i_volume_loud_bold_duotone };
const S_i_wallet = { linear: i_wallet_linear, outline: i_wallet_outline, bold: i_wallet_bold, duotone: i_wallet_bold_duotone };
const S_i_wallet_money = { linear: i_wallet_money_linear, outline: i_wallet_money_outline, bold: i_wallet_money_bold, duotone: i_wallet_money_bold_duotone };
const S_i_wi_fi_router_minimalistic = { linear: i_wi_fi_router_minimalistic_linear, outline: i_wi_fi_router_minimalistic_outline, bold: i_wi_fi_router_minimalistic_bold, duotone: i_wi_fi_router_minimalistic_bold_duotone };
const S_i_widget_4 = { linear: i_widget_4_linear, outline: i_widget_4_outline, bold: i_widget_4_bold, duotone: i_widget_4_bold_duotone };
const S_i_sidebar_minimalistic = { linear: i_sidebar_minimalistic_linear, outline: i_sidebar_minimalistic_outline, bold: i_sidebar_minimalistic_bold, duotone: i_sidebar_minimalistic_bold_duotone };
const S_i_gallery_add = { linear: i_gallery_add_linear, outline: i_gallery_add_outline, bold: i_gallery_add_bold, duotone: i_gallery_add_bold_duotone };
const S_i_gallery_edit = { linear: i_gallery_edit_linear, outline: i_gallery_edit_outline, bold: i_gallery_edit_bold, duotone: i_gallery_edit_bold_duotone };

export const ArrowClockwise: Icon = make(S_i_refresh);
export const ArrowDown: Icon = make(S_i_arrow_down);
export const ArrowLeft: Icon = make(S_i_arrow_left);
export const ArrowLineDown: Icon = make(S_i_download_minimalistic);
export const ArrowRight: Icon = make(S_i_arrow_right);
export const ArrowSquareOut: Icon = make(S_i_square_arrow_right_up);
export const ArrowUp: Icon = make(S_i_arrow_up);
export const ArrowUpRight: Icon = make(S_i_arrow_right_up);
export const Bell: Icon = make(S_i_bell);
export const BellIcon: Icon = make(S_i_bell);
export const BellRinging: Icon = make(S_i_bell_bing);
export const BluetoothIcon: Icon = make(S_i_bluetooth);
export const Broadcast: Icon = make(S_i_play_stream);
export const CalendarBlank: Icon = make(S_i_calendar_minimalistic);
export const CalendarPlus: Icon = make(S_i_calendar_add);
export const Camera: Icon = make(S_i_camera);
export const CameraRotate: Icon = make(S_i_camera_rotate);
export const CaretDoubleLeft: Icon = make(S_i_double_alt_arrow_left);
export const CaretDoubleRight: Icon = make(S_i_double_alt_arrow_right);
export const CaretDown: Icon = make(S_i_alt_arrow_down);
export const CaretDownIcon: Icon = make(S_i_alt_arrow_down);
export const CaretLeft: Icon = make(S_i_alt_arrow_left);
export const CaretRight: Icon = make(S_i_alt_arrow_right);
export const CaretRightIcon: Icon = make(S_i_alt_arrow_right);
export const CaretUp: Icon = make(S_i_alt_arrow_up);
export const CaretUpIcon: Icon = make(S_i_alt_arrow_up);
export const CellSignalLow: Icon = make(S_i_wi_fi_router_minimalistic);
export const ChartBar: Icon = make(S_i_chart_2);
export const ChartDonut: Icon = make(S_i_pie_chart_2);
export const ChartLineUp: Icon = make(S_i_graph_new_up);
export const ChatCircle: Icon = make(S_i_chat_round);
export const ChatCircleDots: Icon = make(S_i_chat_round_dots);
export const ChatText: Icon = make(S_i_chat_line);
export const Check: Icon = make(S_i_check_read);
export const CheckCircle: Icon = make(S_i_check_circle);
export const CheckIcon: Icon = make(S_i_check_read);
export const Clock: Icon = make(S_i_clock_circle);
export const ClockCounterClockwise: Icon = make(S_i_history);
export const CodeIcon: Icon = make(S_i_code_2);
export const Coins: Icon = make(S_i_money_bag);
export const Compass: Icon = make(S_i_compass);
export const Copy: Icon = make(S_i_copy);
export const CornersOut: Icon = make(S_i_full_screen);
export const CreditCardIcon: Icon = make(S_i_card);
export const Crown: Icon = make(S_i_crown);
export const CurrencyBtc: Icon = make(S_i_wallet_money);
export const CurrencyDollar: Icon = make(S_i_dollar);
export const Diamond: Icon = make(S_i_cup_star);
export const DotsThree: Icon = make(S_i_menu_dots);
export const DotsThreeOutlineIcon: Icon = make(S_i_menu_dots);
export const DotsThreeVerticalIcon: Icon = make(S_i_menu_dots_vertical);
export const DownloadIcon: Icon = make(S_i_download);
export const EnvelopeIcon: Icon = make(S_i_letter);
export const Eye: Icon = make(S_i_eye);
export const EyeIcon: Icon = make(S_i_eye);
export const EyeSlash: Icon = make(S_i_eye_closed);
export const Faders: Icon = make(S_i_tuning_2);
export const FileIcon: Icon = make(S_i_document);
export const FileTextIcon: Icon = make(S_i_document_text);
export const Fire: Icon = make(S_i_fire);
export const Flag: Icon = make(S_i_flag);
export const FloppyDiskIcon: Icon = make(S_i_diskette);
export const FolderIcon: Icon = make(S_i_folder);
export const FolderOpenIcon: Icon = make(S_i_folder_open);
export const FunnelSimple: Icon = make(S_i_filter);
export const GameController: Icon = make(S_i_gamepad);
export const GearIcon: Icon = make(S_i_settings);
export const Gift: Icon = make(S_i_gift);
export const GraduationCap: Icon = make(S_i_square_academic_cap);
export const HandWaving: Icon = make(S_i_hand_stars);
export const Heart: Icon = make(S_i_heart);
export const HeartBreak: Icon = make(S_i_heart_broken);
export const HeartStraight: Icon = make(S_i_heart);
export const House: Icon = make(S_i_home_smile);
export const HouseLine: Icon = make(S_i_home_2);
/** A picture with a plus — add a cover. */
export const ImageSquare: Icon = make(S_i_gallery_add);
/** A picture with a pencil — change a cover. */
export const ImageEdit: Icon = make(S_i_gallery_edit);
export const Info: Icon = make(S_i_info_circle);
export const Key: Icon = make(S_i_key);
export const KeyboardIcon: Icon = make(S_i_keyboard);
export const LayoutIcon: Icon = make(S_i_widget_4);
export const Lightning: Icon = make(S_i_bolt);
export const List: Icon = make(S_i_hamburger_menu);
export const ListBullets: Icon = make(S_i_list);
export const Lock: Icon = make(S_i_lock);
export const MagnifyingGlass: Icon = make(S_i_magnifer);
export const MagnifyingGlassIcon: Icon = make(S_i_magnifer);
export const Microphone: Icon = make(S_i_microphone);
export const MicrophoneSlash: Icon = make(S_i_muted);
export const Monitor: Icon = make(S_i_monitor);
export const MonitorArrowUp: Icon = make(S_i_screen_share);
export const MonitorIcon: Icon = make(S_i_monitor);
export const MonitorPlay: Icon = make(S_i_tv);
export const MoonIcon: Icon = make(S_i_moon);
export const MoonStars: Icon = make(S_i_moon_stars);
export const PaletteIcon: Icon = make(S_i_palette);
export const PaperPlaneRight: Icon = make(S_i_plain_2);
export const PictureInPicture: Icon = make(S_i_pip);
export const Play: Icon = make(S_i_play);
export const PlayCircle: Icon = make(S_i_play_circle);
export const Plus: Icon = make(S_i_add);
export const PlusIcon: Icon = make(S_i_add);
export const Prohibit: Icon = make(S_i_forbidden_circle);
export const Pulse: Icon = make(S_i_pulse);
export const PushPin: Icon = make(S_i_pin);
export const Question: Icon = make(S_i_question_circle);
export const QuestionIcon: Icon = make(S_i_question_circle);
export const Receipt: Icon = make(S_i_bill_list);
export const Rows: Icon = make(S_i_list);
export const SealCheck: Icon = make(S_i_verified_check);
export const ShareFat: Icon = make(S_i_share);
export const ShareNetwork: Icon = make(S_i_share_circle);
export const Shield: Icon = make(S_i_shield);
export const ShieldIcon: Icon = make(S_i_shield);
export const ShieldStar: Icon = make(S_i_shield_star);
export const Sidebar: Icon = make(S_i_sidebar);
/** A panel and its rail. Solar draws the rail on the right — pass `mirrored` for a left-hand sidebar. */
export const SidebarSimple: Icon = make(S_i_sidebar_minimalistic);
export const SignIn: Icon = make(S_i_login_2);
export const SignOut: Icon = make(S_i_logout_2);
export const SignOutIcon: Icon = make(S_i_logout_2);
export const Smiley: Icon = make(S_i_smile_circle);
export const Sparkle: Icon = make(S_i_stars);
export const SpeakerHigh: Icon = make(S_i_volume_loud);
export const SpeakerSlash: Icon = make(S_i_volume_cross);
export const SquaresFour: Icon = make(S_i_widget_4);
export const Stop: Icon = make(S_i_stop);
export const Storefront: Icon = make(S_i_shop);
export const SunIcon: Icon = make(S_i_sun);
export const Sword: Icon = make(S_i_bolt_circle);
export const Tag: Icon = make(S_i_tag);
export const Target: Icon = make(S_i_target);
export const Ticket: Icon = make(S_i_ticket);
export const Timer: Icon = make(S_i_stopwatch);
export const TranslateIcon: Icon = make(S_i_translation);
export const Trash: Icon = make(S_i_trash_bin_trash);
export const TrendUp: Icon = make(S_i_graph_up);
export const Trophy: Icon = make(S_i_cup_star);
export const User: Icon = make(S_i_user_rounded);
export const UserIcon: Icon = make(S_i_user_rounded);
export const UserPlus: Icon = make(S_i_user_plus_rounded);
export const Users: Icon = make(S_i_users_group_two_rounded);
export const UsersThree: Icon = make(S_i_users_group_rounded);
export const VideoCamera: Icon = make(S_i_videocamera);
export const VideoCameraSlash: Icon = make(S_i_videocamera_off);
export const Wallet: Icon = make(S_i_wallet);
export const Warning: Icon = make(S_i_danger_triangle);
export const WarningCircle: Icon = make(S_i_danger_circle);
export const X: Icon = make(drawn('<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" d="M18 6 6 18M6 6l12 12"/>', '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2.2" d="M18 6 6 18M6 6l12 12"/>'));
export const XIcon: Icon = make(drawn('<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" d="M18 6 6 18M6 6l12 12"/>', '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2.2" d="M18 6 6 18M6 6l12 12"/>'));

/**
 * The WorldSpace menu mark: a long line over a half one — the socials app's
 * menu button (MobileNavigation), used for the rail's collapse control and
 * the phone's menu so the two apps share one gesture.
 */
export const MenuHalf: Icon = ({ size = "1em", color = "currentColor", mirrored, className, style, ...rest }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="0 0 20 20"
    fill="none"
    color={color}
    className={className}
    style={mirrored ? { ...style, transform: "scaleX(-1)" } : style}
    aria-hidden={rest["aria-label"] ? undefined : true}
    {...rest}
  >
    <path d="M3 7h14M3 13h7" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
  </svg>
);
